#kubectl.exe create deployment nginx-for-svc --image=nginx --replicas=2 --port=80
apiVersion: v1
kind: Service
metadata:
    name: nodeport-service
spec:
    type: NodePort
    selector:
        app: nginx-for-svc
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080